In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def get_usersjar():
    usersjar = "/home/yao/Software/users.jar"
    return usersjar

def query_fermigbrst(cdir='./'):
    fermigbrst = cdir+'/fermigbrst_test.txt'
    if not os.path.exists(fermigbrst):
        usersjar = get_usersjar()
        assert os.path.exists(usersjar), """'users.jar' is not available! 
            download users.jar at:
            https://heasarc.gsfc.nasa.gov/xamin/distrib/users.jar
            and update the path of usersjar in 'personal_settings.py'."""
        java_ready = os.system("java --version")
        assert not java_ready, """java not properly installed!
            Install Oracle Java 10 (JDK 10) in Ubuntu or Linux Mint from PPA
            $ sudo add-apt-repository ppa:linuxuprising/java
            $ sudo apt update
            $ sudo apt install oracle-java10-installer"""
        fields = ("trigger_name,t90,t90_error,t90_start,"
            "Flnc_Band_Epeak,scat_detector_mask")
        print('querying fermigbrst catalog using HEASARC-Xamin-users.jar ...')
        query_ready = os.system("java -jar "+usersjar+" table=fermigbrst fields="
                +fields+" sortvar=trigger_name output="+cdir+"/fermigbrst_test.txt")
        assert not query_ready, 'failed in querying fermigbrst catalog!'
        print('successful in querying fermigbrst catalog!')
    return fermigbrst

fermigbrst = query_fermigbrst()

In [2]:
df = pd.read_csv(fermigbrst,delimiter='|',header=0,skipfooter=3,engine='python')
trigger_name = df['trigger_name'].apply(lambda x:x.strip()).values
t90_str = df[df.columns[1]].apply(lambda x:x.strip()).values
print(df.columns[1])
t90_error_str = df[df.columns[2]].apply(lambda x:x.strip()).values
t90_start_str = df[df.columns[3]].apply(lambda x:x.strip()).values
Flnc_Band_Epeak_str = df[df.columns[4]].apply(lambda x:x.strip()).values
scat_detector_mask_str = df[df.columns[5]].apply(lambda x:x.strip()).values
burst_number = len(trigger_name)
print('burst_number = ',burst_number)


t90    
burst_number =  2650


In [3]:
bnname='bn110920546'

In [4]:
bnname in trigger_name

True

In [5]:
number=trigger_name.tolist().index(bnname)

In [6]:
trigger_name[number]

'bn110920546'

In [7]:
t90_str[number]

'160.771'

In [8]:
type(t90_str[number])

str

In [9]:
t90 =float(t90_str[number])
t90

160.771

In [10]:
t90_start_str[number]

'5.120'

In [11]:
########

scat_detector_mask_str[number]

'11010000000010'

In [12]:
scat_detector_mask_list=list(scat_detector_mask_str)

In [13]:
import re
a = [m.start() for m in re.finditer('1', scat_detector_mask_str[number])]
print (a)

[0, 1, 3, 12]


In [14]:
det=['n0','n1','n2','n3','n4','n5','n6','n7','n8','n9','na','nb','b0','b1']

In [15]:
a[0]

0

In [16]:
type(a[0])

int

In [17]:
print(det[a[0]])

n0


In [18]:
a[:]

[0, 1, 3, 12]

In [19]:
len(a)

4

In [20]:
np.arange(len(a)+1)

array([0, 1, 2, 3, 4])

In [21]:
for i in a[:]:
    b=det[i]+'.pha'
    print(b)

n0.pha
n1.pha
n3.pha
b0.pha


In [22]:
for i in (np.arange(1,4)):
    print(a)

[0, 1, 3, 12]
[0, 1, 3, 12]
[0, 1, 3, 12]


In [23]:
e=(1,2,3)

In [24]:
type(e)

tuple

In [25]:
tuple(a)

(0, 1, 3, 12)

In [26]:
(tuple(np.arange(1,len(a)+1)))

(1, 2, 3, 4)

In [27]:
for i in (1,2,3,4):
    print(a)

[0, 1, 3, 12]
[0, 1, 3, 12]
[0, 1, 3, 12]
[0, 1, 3, 12]


In [34]:
for i in (np.arange(1)+1):
    print(a)

[0, 1, 3, 12]


In [ ]:
type(tuple(np.arange(1,len(a)+1)))

In [ ]:
for i in (np.arange(1,len(a)+1)):
    print(a)

In [ ]:
np.arange(1,1+len(a))

In [33]:
type(np.arange(1,a+1))

TypeError: can only concatenate list (not "int") to list

In [35]:
np.arange(1,len(a)+1)


array([1, 2, 3, 4])

In [41]:
t=(np.arange(1,len(a)+1))

In [37]:
type(1)

int

In [38]:
type((np.arange(1,len(a)+1)))

numpy.ndarray

In [39]:
int(np.arange(1,len(a)+1))

TypeError: only size-1 arrays can be converted to Python scalars

In [42]:
label_list = [int(i) for i in t]

In [43]:
label_list

[1, 2, 3, 4]

In [50]:
type(a)

list

In [44]:
type(label_list)

list

In [46]:
end_a=t.astype(int)

In [47]:
type(end_a)

numpy.ndarray

In [48]:
end_a

array([1, 2, 3, 4])

In [52]:
print(t.astype(int))

[1 2 3 4]


In [58]:
x=np.arange(1,len(a)+1)
print(x)

[1 2 3 4]


In [62]:
for i in range(1,5):
    
    print(i,type(i))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
